### ISSUE TITLE
implement snapshot handling

### ISSUE THREAD

**Issue by crpb** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update#13]
## [OPNsense 24.7.3 released](https://forum.opnsense.org/index.php?topic=42541.0)

> But that is not all.  The GUI gains snapshot support on ZFS installations by
> implementing what is called "boot environments" which allows one to move
> seamlessly from one snapshot to another via reboot.  This functionality can
> also be accessed from the boot loader menu option "8" for a quick recovery
> ensuring that at least one other snapshot was created to boot into.  A very
> special thank you to Sheridan Computers for contributing this feature.
### [OPNsense docs - Snapshots](https://docs.opnsense.org/manual/snapshots.html#)

[actions_zfs](https://github.com/opnsense/core/blob/stable/24.7/src/opnsense/service/conf/actions.d/actions_zfs.conf)
```
> configctl |grep zfs
zfs trim [ ZFS pool trim ]
zfs scrub [ ZFS pool scrub ]
zfs snapshot list [  ]
zfs snapshot create [  ]
zfs snapshot clone [  ]
zfs snapshot activate [  ]
zfs snapshot destroy [  ]
zfs snapshot rename [  ]
zfs snapshot supported [  ]
```

```
> configctl zfs snapshot list |jq
[
  {
    "uuid": "b185610f-c8d5-3d61-a453-1bd857f7cbf8",
    "name": "24.7.3_1-20240905-0300",
    "active": "-",
    "mountpoint": "-",
    "size": "4.98M",
    "created_str": "2024-09-05 03:00",
    "created": 1725498000.0
  },
  {
    "uuid": "fe5fc0a4-917b-3701-a4ed-60120b6930cc",
    "name": "fine",
    "active": "NR",
    "mountpoint": "/",
    "size": "1.81G",
    "created_str": "2024-09-05 02:47",
    "created": 1725497220.0
  }
]
```

I think it might be a good idea to automatically create snapshots before an upgrade takes place.

- As a naming scheme i would suggest something like `$(opnsense-version -v)-last` / `24.7.3_1-last` (or preupgrade.. something..)
   - the date will be stored so it mustn't be used in the name.. `¯\_(ツ)_/¯`

- After the succesfull upgrade maybe an additional snapshot `$(opnsense-version -v)-[first|something..]`

- then there is also the activation for the next boot which could be automated aswell, but most likely optional as default?

🙈 🙊 🙉

**Comment by zerwes** [comment]
Hello @crpb - whow - what a good point
I can remember at least one upgrade that broke a lot of porcelain leaving me with a broken system, headaches and trembling sweaty hands on the keyboard - would have saved me a lot!
(well, our main production opnsense boxes come form ancient versions and still use ufs so maybe this feature would be the last kick to convince me to re-install them!)
Cool feature and thank you @crpb for the hint.
I will try to investigate some time here with my colleagues)
If you have some working examples, tests, proposals etc. - support and contributions are always welcome as our resources are limited.
