### ISSUE TITLE
undefined timeout var with force option

### ISSUE THREAD

**Issue by crpb** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update#15]
Hey,

i ran `ansible-playbook -v -e opn_update_force=true -D update.yaml -l ...`  which failed and after double checking on my test vm it seems this happens when the system is already on the latest version. 

```
fatal: [192.168.1.5]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: '_opn_reboot_timeout' is undefined. '_opn_reboot_timeout' is undefined

    The error appears to be in '/home/cb/git/github/rosa-luxemburgstiftung-berlin/ansible-opnsense-update/tasks/update.yml': line 83, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - name: "run update and reboot using a reboot_timeout of {{ _opn_reboot_timeout }}s ..."
      ^ here
    We could be wrong, but this one looks like it might be an issue with
    missing quotes. Always quote template expression brackets when they
    start a value. For instance:

        with_items:
          - {{ foo }}

    Should be written as:

        with_items:
          - "{{ foo }}"
[192.168.1.5] TASK: ansible-opnsense-update : run update and reboot using a reboot_timeout of {{ _opn_reboot_timeout }}s ... (debug)> c

```

witth `-e _opn_reboot_timeout=5` it works but starts a timeout for a reboot which doesn't happen.
Full log of `ANSIBLE_NOCOWS=1 ANSIBLE_DEBUG=1 ANSIBLE_ENABLE_TASK_DEBUGGER=false ansible-playbook -v -e opn_update_force=true -D update.yaml -l opnsensetest --tags update  -e _opn_reboot_timeout=5  |& tee ~/opnsense-force-update.txt` attached.
[opnsense-force-update.txt](https://github.com/user-attachments/files/17515793/opnsense-force-update.txt)

**Comment by zerwes** [comment]
Hello @crpb 
thank you for the report
should be fixed
