### ISSUE TITLE
SOLVED Can't upgrade from 22.1.6 to *.7

### ISSUE THREAD

**Issue by mircsicz** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update#3]
Hi all,

maybe I'm simply just to new to whole ball-game but I can't see a mistake in how I'm using your roles or how I setup my playbook:

`
TASK [ansible-opnsense-update : register desired base version] *******************************
task path: /Users/mircsicz/Nextcloud/Configs/ansible/roles/ansible-opnsense-update/tasks/update.yml:10
fatal: [one-bh-r]: FAILED! => {"msg": "template error while templating string: No filter named 'split'.. String: {{ opn_update_desired_version | split('.') }}"}

PLAY RECAP ***********************************************************************************
one-bh-r                   : ok=9    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

`

I've tried running it with that cmd:

`ansible-playbook -i hosts_one_inv.yml -v -e opn_update_desired_version=22.1 -e opn_update_force=true --extra-vars "machines=one-bh-r" play_opn-update.yml -K -v
`
As this failed I added the minor version: opn_update_desired_version=22.1.7 sadly that didn't solve the problem...

In case your wondering about the extra-var machines, this is my play:

`
---
  - name: opnsense
    hosts: "{{ machines }}"
    vars:
      ansible_become: true
    roles:
     - role: ~/ansible/roles/ansible-opnsense-facts
       tags:
         - opnsense
         - facts
     - role: ~/ansible/roles/ansible-opnsense-update
       tags:
         - opnsense
         - update
`

Hoping for a hint...

P.S.: yes I've just downloaded and setup your roles two days ago so I did not yet have a chance to successfully test them :-(

**Comment by zerwes** [comment]
Can you please give me some details on the ansible version used?
The missing split filter is a ansible issue, and not the matter of the playbook.
Please send the output of `ansible --version`

**Comment by mircsicz** [comment]
Thank's for your reply <3

`
ansible 2.9.27
  config file = None
  configured module search path = ['/Users/mircsicz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible@2.9/2.9.27_2/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/opt/ansible@2.9/bin/ansible
  python version = 3.9.12 (main, Mar 26 2022, 15:52:10) [Clang 13.0.0 (clang-1300.0.29.30)]
`

**Comment by zerwes** [comment]
Well, you need at least ansible 2.11
... in fact there is a check that ensures this
https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/blob/main/tasks/main.yml#L4:L9
I am wondering why this check was failing ...
Can you please give me the value of `{{ ansible_version.full }}` for your version?

**Comment by mircsicz** [comment]
Sorry my bad, forgot about that detail after struggling with it during the setup:

As there's no version 2.11 available (on MacOS through homebrew) I disabled that test and then forgot about it when trying to run my first upgrade with it :-(

I'll try on linux!
