### ISSUE TITLE
implement a dual-step / multi-step upgrade

### ISSUE THREAD

**Issue by zerwes** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update#6]
For example, if the current version is `22.7.11` and `23.1` is released, using `opn_update_force=true` will try to perform a direct upgrade to `23.1` ... and this will not work!
So currently we need 2 ansible runs:

1. using `-e opn_update_desired_version=22.7.11_1` (no reboot required)
2. followed by one using `-e opn_update_desired_version=23.1` or `-e opn_update_force=true`

So as a default we should choose the next available release and using `opn_update_force=true` we should iterate over all available versions ...

**Comment by zerwes** [comment]
22.7.11_1 is not in the changelog fact ...

**Comment by zerwes** [comment]
`# tail -11 /usr/local/opnsense/scripts/firmware/reboot.sh`
```
# Additionally return the next version number if an update to the
# core package is available.  We want to use it to display additional
# information in the shell menu including the matching changelog.

if [ -n "${LQUERY}" -a -n "${RQUERY}" -a \
    "$(${PKG} version -t ${LQUERY} ${RQUERY})" = "<" ]; then
	echo ${RQUERY%%_*}
fi

# success is reboot:
exit ${WANT_REBOOT}
```

**Comment by zerwes** [comment]
next version working as expected:
```
# opnsense-version
OPNsense 23.1_6
# /usr/local/opnsense/scripts/firmware/reboot.sh
23.1.1
```

**Comment by zerwes** [comment]
question is: how will this behave if there is a major update in the pipe with a minor one between ...?

**Comment by zerwes** [comment]
|Package name|Current version|New version|Required action|Repository|
|------------|---------------|-----------|---------------|----------|
|opnsense    |	23.1.1       |   23.1.1_2| upgrade       |OPNsense  |

but

```
# /usr/local/opnsense/scripts/firmware/reboot.sh; echo $?
23.1.1
1
```

**Comment by zerwes** [comment]
`-e opn_update_force=true` works in this case as expected
`The following 1 package(s) will be affected (of 0 checked):\n\nInstalled packages to be UPGRADED:\n\topnsense: 23.1.1 -> 23.1.1_2`
and after the update:
```
# opnsense-version 
OPNsense 23.1.1_2
```

**Comment by crpb** [comment]
i was wondering if it would be a good idea to make use of [check.sh](https://github.com/opnsense/core/blob/master/src/opnsense/scripts/firmware/check.sh) to detect the next safe upgrade-path so you could just use something like `opn_auto_update=True` instead of the `opn_update_force` which might result in issues when one of many systems is on a much older version than the rest.

this should also help with with an upgrade-till-latest mechanism.


here an quick overview
```sh
% for f in *.json ; do echo $f; cat $f |jq '{product_version, needs_reboot, upgrade_needs_reboot}, [.upgrade_sets[]|{name, new_version, current_version}], [.upgrade_packages[]|select(.name=="opnsense")|{new_version, current_version}] |del(select(length == 0))//empty?' ; done
pkg_upgrade.23.7.12_5.json
{
  "product_version": "23.7.12_5",
  "needs_reboot": "0",
  "upgrade_needs_reboot": "1"
}
[
  {
    "name": "packages",
    "new_version": "24.1",
    "current_version": "23.7"
  },
  {
    "name": "kernel",
    "new_version": "24.1",
    "current_version": "23.7.10"
  },
  {
    "name": "base",
    "new_version": "24.1",
    "current_version": "23.7.10"
  }
]
pkg_upgrade.23.7.5.json
{
  "product_version": "23.7.5",
  "needs_reboot": "1",
  "upgrade_needs_reboot": "0"
}
[
  {
    "new_version": "23.7.12_5",
    "current_version": "23.7.5"
  }
]
pkg_upgrade.24.1.1.json
{
  "product_version": "24.1.1",
  "needs_reboot": "1",
  "upgrade_needs_reboot": "0"
}
[
  {
    "new_version": "24.1.3_1",
    "current_version": "24.1.1"
  }
]
pkg_upgrade.24.1.2_1.json
{
  "product_version": "24.1.2_1",
  "needs_reboot": "0",
  "upgrade_needs_reboot": "0"
}
[
  {
    "new_version": "24.1.3_1",
    "current_version": "24.1.2_1"
  }
]
pkg_upgrade.24.1.3_1.json
{
  "product_version": "24.1.3_1",
  "needs_reboot": "0",
  "upgrade_needs_reboot": "0"
}
```
complete files:
[pkg_upgrade.23.7.5.json](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/files/14622643/pkg_upgrade.23.7.5.json)
[pkg_upgrade.23.7.12_5.json](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/files/14622642/pkg_upgrade.23.7.12_5.json)
[pkg_upgrade.24.1.1.json](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/files/14622644/pkg_upgrade.24.1.1.json)
[pkg_upgrade.24.1.2_1.json](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/files/14622666/pkg_upgrade.24.1.2_1.json)
[pkg_upgrade.24.1.3_1.json](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/files/14622667/pkg_upgrade.24.1.3_1.json)

**Comment by zerwes** [comment]
@crpb thank you for the hint
I'll have a look at this option (but I must admit this topic is not tagged with a high priority for me at the moment ...)

**Comment by zerwes** [comment]
`JSONFILE="/tmp/pkg_upgrade.json"`
TODO: install outdated version and test this

@crpb sorry, as I told you, this is not of high priority for us at the moment. so if you like to speed this up and give us a helping hand, pls create at least a draft as a PR ...

**Comment by crpb** [comment]
Hey, yeah no problem here. /me is currently very busy with work. And the comming week doesn't look either.. 

But I also wouldn't really know where to start. My Ansible Kung-Foo is very bad and that makes it harder to have a look when i had like 30minutes and was eager o_0. In that time nothing is done and more confusion is gathered \*kicher*. 

And yeah, for those couple json-dumps i had to do some loops and often took snapshots in virtsh and/or virt-manager.

**Comment by zerwes** [comment]
Hello @crpb 
Everybody is busy all day and has no time to play ... :-)
No problem, if you can give me some hints about your steps to get the json files I can have a look at this.
Just the commands you used might give me the hint into the right direction ... I assume it will be no big stuff to put this in ansible ...

**Comment by crpb** [comment]
> if you can give me some hints about your steps

hmm.. when i see that correctly in my iso dump on the nas i ended up with [23.1](https://mirror.fra10.de.leaseweb.net/opnsense/releases/23.1/) installed that and than it was basically this and now i see what's missing :-).
```
/usr/local/opnsense/scripts/firmware/check.sh;  cat /tmp/pkg_upgrade.json |jq '{product_version, needs_reboot, upgrade_needs_reboot}, [.upgrade_sets[]|{name, new_version, current_version}], [.upgrade_packages[]|select(.name=="opnsense")|{new_version, current_version}] |del(select(length == 0))//empty?' |tee -a /conf/`date -Iminutes`.json && /usr/local/opnsense/scripts/shell/firmware.sh
```

## This looks quite better..
```
/usr/local/opnsense/scripts/firmware/check.sh;  cp /tmp/pkg_upgrade.json /conf/`date -Iminutes`.json && /usr/local/opnsense/scripts/shell/firmware.sh
```

EDIT: It was check.sh at the end but it must be firmware.sh :-). :EDIT

I extended it with autosaving.
The second run of check.sh will prompt you, which is discarded by the piping, and you can just accept with 'y' or in some cases as you know with the next version-number.

I guess with that you would only have to keep in mind that you should take snapshots if something goes wrong. I certainly needed some because i forgot one and didn't realize it after two or three boot i think..

**Comment by crpb** [comment]
btw, `/usr/local/opnsense/scripts/firmware/register.php resync` for fixing those pkg resolve problems which came up a while ago.

**Comment by zerwes** [comment]
Thank you @crpb ;
I'll have a look at this and will keep you updated ...

**Comment by zerwes** [comment]
current version: 24.1.9 community edition
expected upgrade version: 24.4.1 business edition
```
# cat /tmp/pkg_upgrade.json | jq '{product_version, needs_reboot, upgrade_needs_reboot}, [.upgrade_sets[]|{name, new_version, current_version}], [.upgrade_packages[]|select(.name=="opnsense")|{new_version, current_version}] | del(select(length == 0))//empty?' | tee -a /conf/`date -Iminutes`.json
{
  "product_version": "24.1.9",
  "needs_reboot": "1",
  "upgrade_needs_reboot": "0"
}
```

**Comment by zerwes** [comment]
```
# cat /tmp/pkg_upgrade.json | jq '{product_version, needs_reboot, upgrade_needs_reboot}, [.new_packages[]|{name, version, current_version, new_version}], [.upgrade_packages[]|select(.name=="opnsense")|{new_version, current_version}]' 
{
  "product_version": "24.1.9",
  "needs_reboot": "1",
  "upgrade_needs_reboot": "0"
}
[
  {
    "name": "opnsense-business",
    "version": "24.4.1",
    "current_version": null,
    "new_version": null
  },
  {
    "name": "os-OPNBEcore",
    "version": "1.4_1",
    "current_version": null,
    "new_version": null
  }
]
```

**Comment by zerwes** [comment]
opnsense: 24.1.9 -> 24.1.9_4
```json
cat /tmp/pkg_upgrade.json | jq '{product_version, needs_reboot, upgrade_needs_reboot}, [.upgrade_sets[]|{name, new_version, current_version}], [.upgrade_packages[]|select(.name=="opnsense")|{new_version, current_version}] | del(select(length == 0))//empty?'
{
  "product_version": "24.1.9",
  "needs_reboot": "0",
  "upgrade_needs_reboot": "0"
}
[
  {
    "new_version": "24.1.9_4",
    "current_version": "24.1.9"
  }
]
```

**Comment by crpb** [comment]
i wonder if those results should be implemented in the [facts-script](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-facts/blob/19cefbdb5b37223b3d8db24e51b6d66fbc85f94c/files/opnsense.fact)?

Basically to either run the upgrade in a loop(if thats possible) or at least i could script it localy e.g.

```
% ansible -m setup -o opnsense |sed 's/^.*=> {/{/g'|jq '[.ansible_facts.ansible_local.opnsense.core.product_version, .ansible_facts.ansible_hostname]|@tsv' -r | sort -V
24.1.8  fw-lan0
24.1.8  fw-lan0
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  gate
24.1.8  uniontel
24.1.9_4        gate
24.1.9_4        gate
24.1.9_4        gate
24.1.9_4        gate
24.1.9_4        gate
24.1.9_4        gate
```

**Comment by crpb** [comment]
24.1.10_3->24.1.10_8
```
root@gate:~ # /usr/local/opnsense/scripts/firmware/check.sh > /dev/null ; jq '{product_version, needs_reboot, upgrade_needs_reboot, upgrade_major_version}, [.upgrade_sets[]|{name, current_version, new_version}], [.upgrade_packages[]|select(.name=="opnsense")|{current_version, new_version}] | del(select(length == 0))//empty?' /tmp/pkg_upgrade.json
{
  "product_version": "24.1.10_3",
  "needs_reboot": "0",
  "upgrade_needs_reboot": "0",
  "upgrade_major_version": ""
}
[
  {
    "current_version": "24.1.10_3",
    "new_version": "24.1.10_8"
  }
]
```

major upgrade: 24.1.10_8 -> 24.7
```
# /usr/local/opnsense/scripts/firmware/check.sh > /dev/null ; jq '{product_version, needs_reboot, upgrade_needs_reboot, upgrade_major_version}, [.upgrade_sets[]|{name, current_version, new_version}], [.upgrade_packages[]|select(.name=="opnsense")|{current_version, new_version}] | del(select(length == 0))//empty?' /tmp/pkg_upgrade.json
{
  "product_version": "24.1.10_8",
  "needs_reboot": "0",
  "upgrade_needs_reboot": "1",
  "upgrade_major_version": "24.7"
}
[
  {
    "name": "packages",
    "current_version": "23.7",
    "new_version": "24.7"
  },
  {
    "name": "kernel",
    "current_version": "24.1.8",
    "new_version": "24.7"
  },
  {
    "name": "base",
    "current_version": "24.1.8",
    "new_version": "24.7"
  }
]
```
24.7_5 -> 24.7_9
```
# /usr/local/opnsense/scripts/firmware/check.sh > /dev/null ; jq '{product_version, needs_reboot, upgrade_needs_reboot, upgrade_major_version}, [.upgrade_sets[]|{name, current_version, new_version}], [.upgrade_packages[]|select(.name=="opnsense")|{current_version, new_version}] | del(select(length == 0))//empty?' /tmp/pkg_upgrade.json
{
  "product_version": "24.7_5",
  "needs_reboot": "0",
  "upgrade_needs_reboot": "0",
  "upgrade_major_version": ""
}
[
  {
    "current_version": "24.7_5",
    "new_version": "24.7_9"
  }
]
```

**Comment by crpb** [comment]
> i wonder if those results should be implemented in the [facts-script](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-facts/blob/19cefbdb5b37223b3d8db24e51b6d66fbc85f94c/files/opnsense.fact)?

Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-facts/pull/3

**Comment by crpb** [comment]
`2108-143159 < Chunt> [Forum] OPNsense 24.7.2 released → https://da.gd/I0adlz`

24.7.1 -> 24.7.2
```
> /usr/local/opnsense/scripts/firmware/check.sh > /dev/null ; jq '{product_version, needs_reboot, upgrade_needs_reboot, upgrade_major_version}, [.upgrade_sets[]|{name, current_version, new_version}], [.upgrade_packages[]|select(.name=="opnsense")|{current_version, new_version}] | del(select(length == 0))//empty?' /tmp/pkg_upgrade.json
{
  "product_version": "24.7.1",
  "needs_reboot": "1",
  "upgrade_needs_reboot": "0",
  "upgrade_major_version": ""
}
[
  {
    "current_version": "24.7.1",
    "new_version": "24.7.2"
  }
]
```

**Comment by zerwes** [comment]
interesting parts from json:
```json
    upgrade_packages: [
       {
          "name": "opnsense",
          "repository": "OPNsense",
          "current_version": "24.7",
          "new_version": "24.7.9_1"
        },
        {
          "name": "opnsense-update",
          "repository": "OPNsense",
          "current_version": "24.7",
          "new_version": "24.7.8"
        },{
          "name": "base",
          "size": "133482300",
          "repository": "OPNsense",
          "current_version": "24.7",
          "new_version": "24.7.8"
        },
        {
          "name": "kernel",
          "size": "34092244",
          "repository": "OPNsense",
          "current_version": "24.7",
          "new_version": "24.7.8"
        }
    ]
```

**Comment by zerwes** [comment]
:exclamation: 
```shell
# /etc/ansible/facts.d/opnsense.fact
find: /tmp/pkg_upgrade.json: No such file or directory
```
... fixed in Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-facts#4

**Comment by zerwes** [comment]
BE
```json
         {
           "name": "opnsense-business",                                          
           "repository": "OPNsense",                                             
           "current_version": "24.10_7",                                         
           "new_version": "24.10.1"                                              
         }
```

**Comment by zerwes** [comment]
```yaml
---
# main.yml
- name: debug pkg_upgrade item
  ansible.builtin.include_tasks: pkg_upgrade.yml
  with_items: "{{ ansible_local.opnsense.pkg_upgrade }}"
  loop_control:
    loop_var: pkg_upgrade_item

---
# pkg_upgrade.yml
- name: debug upgrade_packages core
  ansible.builtin.debug:
    var: item
  with_items: "{{ pkg_upgrade_item.upgrade_packages }}"
  when: item.name == ansible_local.opnsense.core.product_id
```

**Comment by zerwes** [comment]
related: #16

**Comment by zerwes** [comment]
`pkg_upgrade.needs_reboot` 0|1

**Comment by zerwes** [comment]
23.7 -> 24.1
```yaml
upgrade_sets: [
        {
            "current_version": "",
            "name": "packages",
            "new_version": "24.1",
            "repository": "OPNsense",
            "size": "754585088"
        },
        {
            "current_version": "23.7.10",
            "name": "kernel",
            "new_version": "24.1",
            "repository": "OPNsense",
            "size": "32841852"
        },
        {
            "current_version": "23.7.10",
            "name": "base",
            "new_version": "24.1",
            "repository": "OPNsense",
            "size": "116680004"
        }
    ]
upgrade_needs_reboot: "1"
upgrade_major_version: "24.1"
upgrade_needs_reboot: "1"
needs_reboot: "0"
```

**Comment by zerwes** [comment]
special case where the core package is not in the list of `upgrade_packages`
**and** product_version is higher then the base current version!
```yaml
product_version: "24.7.10_2"
upgrade_packages: [
        {
            "current_version": "24.7.1",
            "name": "base",
            "new_version": "24.7.10",
            "repository": "OPNsense",
            "size": "134566268"
        },
        {
            "current_version": "24.7.1",
            "name": "kernel",
            "new_version": "24.7.10",
            "repository": "OPNsense",
            "size": "34102168"
        }
    ]
```

**Comment by crpb** [comment]
uh wow, i already am at latest with everything but i could give it at least a couple tries on my local test-vm which currently uses like ~80gb because of various historic snapshots :P.
but i'm kinda lost, should i just use `opn_update_desired_version=XXX.XX` for it?

```
Domain: opnsense
 Name        Creation Time               State     Parent
--------------------------------------------------------------
 23.1        2024-08-21 15:06:58 +0200   running
 23.1.11_2   2024-08-21 15:20:46 +0200   running   23.1
 23.7.5      2024-08-21 15:33:35 +0200   running   23.1.11_2
 23.7.12_5   2024-08-21 15:40:09 +0200   running   23.7.5
 24.7.2      2024-08-21 23:46:52 +0200   running   23.7.12_5
 24.7.3_1    2024-09-27 23:39:15 +0200   running   24.7.2
 24.7.5      2024-09-27 23:47:24 +0200   running   24.7.3_1
 24.7.7      2024-11-07 03:30:25 +0100   running   24.7.5
 24.7.8      2024-11-07 03:40:49 +0100   running   24.7.7
 24.7.10_2   2024-12-06 10:10:14 +0100   shutoff   24.7.8
Tree:
23.1
  |
  +- 23.1.11_2
      |
      +- 23.7.5
          |
          +- 23.7.12_5
              |
              +- 24.7.2
                  |
                  +- 24.7.3_1
                      |
                      +- 24.7.5
                          |
                          +- 24.7.7
                              |
                              +- 24.7.8
                                  |
                                  +- 24.7.10_2
```

**Comment by zerwes** [comment]
Hello @crpb 
The stuff is not yet complete, but it should work.
A test is welcome at any time!
you must switch to the `issue6-multistep-upgrade` branch. (PR #17)
And the idea is to just use `-e opn_update_force=true` on each run and it will just bring you to the next possible release target until you reach the current release and there will be nothing left to do for the playbook (will report changed=0 tasks).

If you do not mind, you can use
`ANSIBLE_LOG_PATH=/tmp/opnsenseupdate$VERSION.log ansible-playbook -v -e opn_update_force=true ....`
where you can set the right version before each run, so we will have some log files to evaluate if things go wrong ...

Good luck!

**Comment by crpb** [comment]
ran a while true loop with a script and everything checked out so far 👍🏼 and it didn't do any nasty with the latest version as it kept running 🙈 
```
% ls -1
update-23.1.log
update-23.1.11_2.log
update-23.7.5.log
update-23.7.12_5.log
update-24.1.5_3.log
update-24.1.10_8.log
update-24.7.1.log
update-24.7.10_2.log
```

**Comment by zerwes** [comment]
@crpb thank you for the test!
similar results here ... https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/pull/17#issuecomment-2532661766

**Comment by zerwes** [comment]
... finally it endet up in a complete refactoring of the role, deprecating opn_update_force and opn_update_desired_version etc.

I initially intended to let the role run several updates in a loop until nothing will be left to do. But in general I think most people will have to perform just a single update step. And for those who really need to perform multiple steps, they might prefer to do this one by one and investigate some time to determine the state of the firewall in between.
And as you already demonstrated, if one really likes, he can run the playbook in a shell loop.

If you like and finde some time for this,  have a look at the last state of the PR/branch - I appreciate your feedback.

**Comment by zerwes** [comment]
https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-update/tree/issue6-multistep-upgrade
